### ISSUE TITLE
The handleConstraint feature to limit joystick movement appears to be broken

### ISSUE THREAD

**Issue by rolinster** [bradhowes/Joystick#12]
I cannot limit the joystick's movement using the 'handleConstraint' property.  I am using version 3.2.0 of the release.  This is reproducible using the included JoyStickView Playground without any modification.  Slide the "Constrain Movement" switch to On and observe that movement is not restricted.

I am using Xcode 14.3.1  with an iOS deployment target of 12.0.  Am I doing something wrong?  Without any luck, I've tried changing the 'handlePositionMode' between 'absolute' and 'relative'.  Has something changed?

**Comment by bradhowes** [comment]
No, I think it is a misunderstanding of my meaning mixed with poor labeling on my part for what I meant by constrained. In the playground example, there are actually two constraints: the first is the pink-ish rectangle that contains the movement of the entire joystick. Then there is the switch button that when on constrains the joystick in the pinkish rectangle to only move up and down -- but the entire base is still able to move anywhere it wants within the confines of the pinkish rectangle.

In the demo app (not the playground), the handle constraint is always enabled so it can only move up and down.

If you want to constrain the base to move in just one direction, simply make it a width of 1 in the dimension you want it to stay put, and make sure that the center of the base is inside it. This is the `movableBounds` parameter. In the playground near line 136 there is the code that sets the `handleConstraint` to a rectangle the limits the travel to only on the Y axis.

Does this make sense?

You could use the same rectangle for both the `movableBounds` and the `handleConstraint` so that the base can only move along the same axis as the handle.

**Comment by rolinster** [comment]
Got it.  Thanks
