### ISSUE TITLE
How to use this library in Objective-c

### ISSUE THREAD

**Issue by mohamedaslam** [bradhowes/Joystick#7]
I can able to load and drag joystick in objective-c but iam not able to getting angle and displacement value..
How can i access below method in objective-c.

let monitor: JoyStickViewPolarMonitor = {
    print("\(String(format: "%.2f°", $0.angle)) \(String(format: "%.3f", $0.displacement))")
}

joystick.monitor = .polar(monitor: monitor2)

**Comment by bradhowes** [comment]
Hi. I think something like this should be possible (untested):

```
extension JoyStickView {
    @objc public func setPolarMonitor(_ block: @escaping (CGFloat, CGFloat) -> Void) {
        let bridge = {(report: JoyStickViewPolarReport) in
            block(report.angle, report.displacement)
        }
        monitor = .polar(monitor: bridge)
    }
}
```

AFAIK, Swift and Objective-C blocks are pretty much interchangeable, so you should then be able to do something like this in Objective-C (untested):

```
[joyStickView setPolarMonitor:^ (CGFloat angle, CGFloat displacement) {
  NSLog("angle: %f displacement: %f", angle, displacement);
}];
```

As you found out the `monitor` property cannot be used directly from Objective-C because it uses types that are not representable in the Objective-C universe. Using the extension above keeps the Swift types in Swift but allows one to inject a generic closure / block by wrapping it in another Swift closure and then doing the bridging between the *Report struct and individual CGFloat values.

Regards,

Brad

**Comment by mohamedaslam** [comment]
@bradhowes its working perfect.....Thank you so much.

**Comment by bradhowes** [comment]
Updated README about extension to support Obj-C blocks for position monitoring.
